### ISSUE TITLE
Support app/assets/builds out of the box?

### ISSUE THREAD

**Issue by excid3** [basecamp/hotwire-spark#11]
With cssbundling-rails or tailwindcss-rails, the `app/assets/builds` folder is the main place to watch for CSS files.

Would it make sense to include this folder in the engine's default config? Happy to make a PR if so!

https://github.com/basecamp/hotwire-spark/blob/c8ce327654dc370ce8c217d984e59d6614bad1c0/lib/hotwire/spark/engine.rb#L11

```ruby
      css_paths: %w[ app/assets/stylesheets app/assets/builds ],
```

**Comment by jorgemanrubia** [comment]
Yes @excid3 thanks, go for it! 

We're interested in supporting jsbundling and cssbundling out of the box, even if we didn't target those in the initial version.
