### ISSUE TITLE
NameError: uninitialized constant Hotwire::Spark::Version (NameError)

### ISSUE THREAD

**Issue by thisIsLoading** [basecamp/hotwire-spark#14]
Hey,

thanks for your christmas present!

getting above error on server startup. i tried v0.1.2 as well as via github: 'basecamp/hotwire-spark'

```
NameError: uninitialized constant Hotwire::Spark::Version (NameError)

    @mod.const_get(@cname, false)
        ^^^^^^^^^^
Did you mean?  Hotwire::Spark::VERSION
```

rails console has the same opinion:

```
xxx(dev)> Hotwire::Spark::Version
(xxx):2:in `<main>': uninitialized constant Hotwire::Spark::Version (NameError)

Hotwire::Spark::Version
              ^^^^^^^^^
Did you mean?  Hotwire::Spark::VERSION
xxx(dev)> 
xxx(dev)> Hotwire::Spark::VERSION
=> "0.1.2"
```

**Comment by thisIsLoading** [comment]
if its important, i am on rails 8.0.1

**Comment by jorgemanrubia** [comment]
Oh weird! Thanks for the report @thisIsLoading. I can't reproduce on my side. It's weird because the engine requires that file explicitly [here](https://github.com/basecamp/hotwire-spark/blob/4bba90d537a9632c781f480267a67fbda9b6ea43/lib/hotwire-spark.rb#L1), so it should exist. 

Could you try to reproduce with a fresh Rails app? A minimal example to reproduce would be super helpful.

**Comment by mspsnd** [comment]
Might be related: I had the same error in the test step of my github action but not locally. I then realized that I accidentally placed the gem in the "group :development, :test do" section of my gemfile instead of the "group :development do" section.

**Comment by thisIsLoading** [comment]
hey @jorgemanrubia  , thank you for checking. that is weird, re not reproduceable. i also created a fresh rails app and it runs. so, unfortunately i dont have a reproduceable example, which obviously sucks. i started the project on rails 8 rc1 and went through 8.0 to 8.0.1. i dont know if this really helps but maybe it does. am trying to dig a little deeper though i am not sure if i can be of great help.

re the require, yeah, i skimmed through the code before reporting, i think the key difference is the `Version` vs. `VERSION`, which is weird on a different level and i have no idea where this is coming from. i saw that constant defined in the version file but why it is trying to access `Version` in capitalized is beyond what my small brains can comprehend

@mspsnd thanks for chiming in, i have mine in a :development exclusive group. but after your comment, i tried it even in the "root" but with the same result.

**Comment by mediafinger** [comment]
I can run the console and the server - and it reloads as expected. But I do get the same error message when running the `rake zeitwerk:check` task.

* ruby 3.4.0.preview2
* rails 8.0.1
* hotwire-Spark 0.1.3
* zeitwerk 2.7.1
* _and a heap of other dependencies..._

```shell
$> bin/rails zeitwerk:check

Hold on, I am eager loading the application.
bin/rails aborted!
NameError: uninitialized constant Hotwire::Spark::Version (NameError)

    @mod.const_get(@cname, false)
        ^^^^^^^^^^
Did you mean?  Hotwire::Spark::VERSION

Tasks: TOP => zeitwerk:check
```

**Comment by thisIsLoading** [comment]
hey @mediafinger this is it! i had a relic in my development.rb `config.rake_eager_load = true`, becasue of some reload! issue i had a couple months ago.

after commenting that out, the issue disappears

thanks for posting this!

**Comment by jorgemanrubia** [comment]
[FIx coming here](https://github.com/basecamp/hotwire-spark/pull/22)

**Comment by thisIsLoading** [comment]
excellent, thanks so much @jorgemanrubia for this turbo fix
