### ISSUE TITLE
undefined method `hotwire' for #<Rails::Application::Configuration:0x00000000007648> (NoMethodError)

### ISSUE THREAD

**Issue by t2** [basecamp/hotwire-spark#15]
Rails 7.1.3.4

Added the gem to the development group and ran `bundle install`

Updated `development.rb`

```ruby
config.hotwire.spark.html_paths += ['app/components']
config.hotwire.spark.stimulus_paths += ['app/components']
```

Received error:

```gems/railties-7.1.3.4/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `hotwire' for #<Rails::Application::Configuration:0x00000000007648> (NoMethodError)```

**Comment by robzolkos** [comment]
I think you need Rails 8+ for this.

**Comment by t2** [comment]
Thank you!
