### ISSUE TITLE
On Rails < 8 a stub version gets installed

### ISSUE THREAD

**Issue by frenkel** [basecamp/hotwire-spark#21]
I just followed the README and got confused because it didn't seem to work. After some digging I discovered version 0.0.1 of the gem was installed and it doesn't contain any functionality. It seems the actual working versions require Rails 8.0 but those did not get installed because I'm still on Rails 7.2. You might want to yank 0.0.1 from Rubygems to avoid this confusion or change the README with something like:
```
gem "hotwire-spark", "> 0.0.1"
```

**Comment by jorgemanrubia** [comment]
Thanks for the heads up @frenkel. I just yanked it.
