### ISSUE TITLE
Deleted stimulus controllers do not get unregistered

### ISSUE THREAD

**Issue by KonnorRogers** [basecamp/hotwire-spark#25]
I noticed when using the reloader, modified controllers get unloaded -> reloaded, however, deleted stimulus controllers do not get removed.

Reproduction: https://github.com/KonnorRogers/hotwire-spark-test

**Comment by jorgemanrubia** [comment]
Good one. I'll fix 👍

**Comment by jorgemanrubia** [comment]
[Fix coming here](https://github.com/basecamp/hotwire-spark/pull/29)

I need to test a bit more with a real app. I'll do tomorrow.
