### ISSUE TITLE
Rails console: [ActionCable] Broadcasting to hotwire_spark

### ISSUE THREAD

**Issue by jacob-carlborg-apoex** [basecamp/hotwire-spark#27]
I don't have an experience with ActionCable but I just tried this gem and every time a file is modified the following message appears in the Rails console:

```
[ActionCable] Broadcasting to hotwire_spark: {:action=>:reload_html, :path=>"<path>"}
```

Where `<path>` is the path that was changed.

This occurs in a newly generated Rails 8 application with the only change of adding the hotwire-spark gem.

**Comment by jorgemanrubia** [comment]
Yes @jacob-carlborg-apoex that's expected behavior. With the gem installed, the server starts a thread that listens to file changes. When a change it's detected, it broadcasts a message with details about the change, so that the client can perform whatever reload operation is needed.

**Comment by jacob-carlborg-apoex** [comment]
I do understand the concept, by why does it need to print this to the Rails console? That's not the client, it's the browser, right?

**Comment by jacob-carlborg-apoex** [comment]
I think I see what's going on now. It's not just the server that starts a thread, the Rails console starts a thread that listens to file changes as well. Can't that be avoided? BTW, this causes the browser to reload twice.
